// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4WezVfPC887EUa2jzhzpiOD58EMd9mIo',
    appId: '1:968613961854:web:172a203fbc7fbafaacf82f',
    messagingSenderId: '968613961854',
    projectId: 'groupstudy-aaf7e',
    authDomain: 'groupstudy-aaf7e.firebaseapp.com',
    storageBucket: 'groupstudy-aaf7e.appspot.com',
    measurementId: 'G-EHNLV8K7ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRoXsMRomdnPjdP0KRmXFervkmFCNPWqc',
    appId: '1:968613961854:android:086dc24a203a7911acf82f',
    messagingSenderId: '968613961854',
    projectId: 'groupstudy-aaf7e',
    storageBucket: 'groupstudy-aaf7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSIiLNQaH0q909g6cy9kKv21CvwrQvRF4',
    appId: '1:968613961854:ios:426f7d122de84dc2acf82f',
    messagingSenderId: '968613961854',
    projectId: 'groupstudy-aaf7e',
    storageBucket: 'groupstudy-aaf7e.appspot.com',
    androidClientId: '968613961854-hhvd26lhhiepcpf6djd8aav1e4e177o7.apps.googleusercontent.com',
    iosClientId: '968613961854-9v8887abl15iuumlmtikjhtr443quoa5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fGroupStudy',
  );
}
